//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.18 at 11:26:14 AM IST 
//


package project.transaction.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="amount1" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="amount2" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "username",
    "amount1",
    "amount2"
})
@XmlRootElement(name = "listTransactionRequest")
public class ListTransactionRequest {

    @XmlElement(required = true)
    protected String username;
    protected int amount1;
    protected int amount2;

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsername(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the amount1 property.
     * 
     */
    public int getAmount1() {
        return amount1;
    }

    /**
     * Sets the value of the amount1 property.
     * 
     */
    public void setAmount1(int value) {
        this.amount1 = value;
    }

    /**
     * Gets the value of the amount2 property.
     * 
     */
    public int getAmount2() {
        return amount2;
    }

    /**
     * Sets the value of the amount2 property.
     * 
     */
    public void setAmount2(int value) {
        this.amount2 = value;
    }

}
