//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.18 at 11:26:14 AM IST 
//


package project.transaction.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for transaction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="transaction">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TxnId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="TxnFrom" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="TxnAmount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="TxnStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TxnDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TxnTo" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "transaction", propOrder = {
    "txnId",
    "txnFrom",
    "txnAmount",
    "txnStatus",
    "txnDate",
    "txnTo"
})
public class Transaction {

    @XmlElement(name = "TxnId")
    protected int txnId;
    @XmlElement(name = "TxnFrom")
    protected long txnFrom;
    @XmlElement(name = "TxnAmount")
    protected int txnAmount;
    @XmlElement(name = "TxnStatus", required = true)
    protected String txnStatus;
    @XmlElement(name = "TxnDate", required = true)
    protected String txnDate;
    @XmlElement(name = "TxnTo")
    protected long txnTo;

    /**
     * Gets the value of the txnId property.
     * 
     */
    public int getTxnId() {
        return txnId;
    }

    /**
     * Sets the value of the txnId property.
     * 
     */
    public void setTxnId(int value) {
        this.txnId = value;
    }

    /**
     * Gets the value of the txnFrom property.
     * 
     */
    public long getTxnFrom() {
        return txnFrom;
    }

    /**
     * Sets the value of the txnFrom property.
     * 
     */
    public void setTxnFrom(long value) {
        this.txnFrom = value;
    }

    /**
     * Gets the value of the txnAmount property.
     * 
     */
    public int getTxnAmount() {
        return txnAmount;
    }

    /**
     * Sets the value of the txnAmount property.
     * 
     */
    public void setTxnAmount(int value) {
        this.txnAmount = value;
    }

    /**
     * Gets the value of the txnStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxnStatus() {
        return txnStatus;
    }

    /**
     * Sets the value of the txnStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxnStatus(String value) {
        this.txnStatus = value;
    }

    /**
     * Gets the value of the txnDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxnDate() {
        return txnDate;
    }

    /**
     * Sets the value of the txnDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxnDate(String value) {
        this.txnDate = value;
    }

    /**
     * Gets the value of the txnTo property.
     * 
     */
    public long getTxnTo() {
        return txnTo;
    }

    /**
     * Sets the value of the txnTo property.
     * 
     */
    public void setTxnTo(long value) {
        this.txnTo = value;
    }

}
